import { Inter } from "next/font/google";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const Footer = () => {
  return (
    <div className="w-full bg-blue-800 p-3 text-lg text-center text-white ">
      <p>Developed by Sumit</p>
    </div>
  );
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          {<Navbar />}
          {children}
          {<Footer />}
        </div>
      </body>
    </html>
  );
}
